#!/bin/bash
echo "=========================="
echo "Oculus Platform Switcher"
echo "by Turbo Button"
echo "www.turbo-button.com"
echo "=========================="
rm -f "$(pwd)/Assets/Plugins/OculusPlugin.dll"
rm -f "$(pwd)/Assets/Plugins/OculusPlugin.dll.meta"
rm -f "$(pwd)/Assets/Plugins/OculusPlugin.dll.signature"
rm -f "$(pwd)/Assets/Plugins/OculusPlugin.dll.signature.meta"
rm -f "$(pwd)/Assets/Plugins/donotdelete.txt"
rm -f "$(pwd)/Assets/Plugins/donotdelete.txt.meta"
rm -f "$(pwd)/Assets/Plugins/OculusPlugin.bundle.meta"
rm -f "$(pwd)/Assets/Plugins/x86/_x64/OculusPlugin.dll"
rm -f "$(pwd)/Assets/Plugins/x86/_x64/OculusPlugin.dll.meta"
rm -f "$(pwd)/Assets/Plugins/x86/_x64/OculusPlugin.dll.signature.meta"
rm -f "$(pwd)/Assets/Plugins/x86/_x64/OculusPlugin.dll.signature"
rm -rf "$(pwd)/Assets/Plugins/OculusPlugin.bundle"
rm -rf "$(pwd)/Assets/OVR"
rm -rf "$(pwd)/Assets/Moonlight"
read -p "Dumped files. Press any key to continue."
exec /Applications/Unity/Unity.app/Contents/MacOS/Unity -projectPath $(pwd) -executeMethod TBBuildSettings.ImportNewPlatformFiles
